### ISSUE TITLE
VFs may get reseted after being allocated by other pod

### ISSUE THREAD

**Issue by ormergi** [k8snetworkplumbingwg/sriov-cni#219]
### What happened?
In the scenario where pods with SR-IOV interface from the same resource pool are created and deleted a few times, 
the underlying VF may end up with a default configuration instead of the desired one (i.e: no MAC address, no VLAN).

### What did you expect to happen?
The pod underlying VF is to be configured correctly.

### What are the minimal steps needed to reproduce the bug?
Terminal 1: Monitor SR-IOV VFs state on node `worker1`
Terminal 2:
- Create a pod `test` with:
    - `nodeSelector` to node `worker1`.
    - SR-IOV interface with MAC address `02:02:02:02:02`.
- Wait for the pod to be ready.
- Delete the pod `test` in the background and immediately create a similar pod `test2`.
- Wait for pod `test2` to be ready.

After a few iterations, we saw that the pod is Running but looking at the node VFs 
it shows that it's not configured with the desired MAC address.

### Anything else we need to know?
Scripts and manifests I used for reproducing the issue:
https://gist.github.com/ormergi/3ddbf901ddc95baf316b604994285a69 

It seems that when the pod (1) is deleted and CNI cmdDEL command been executed, it will reset the VF whether it's been allocated by another pod or not.

Also, it's not guaranteed that as soon as a pod is disposed its underlying VF is reseted.
It takes 1-2 seconds for it to reset, which seem odd because I would expect all its resource to be free when it's gone.

### Component Versions
Component | Version|
------------------------------|:-------------------:|
|SR-IOV CNI Plugin            |v2.6|
|Multus                       |v3.8|
|SR-IOV Network Device Plugin |v3.3|
|Kubernetes                   |v1.22.2| 
|OS                           |RHEL 8.6|

### Config Files
Config file locations may be config dependent.

##### CNI config (Try '/etc/cni/net.d/')
```
cat /etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "capabilities": {"portMappings": true}, "logLevel": "debug", "logFile": "/var/log/multus.log", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "cniVersion": "0.3.1", "name": "kindnet", "plugins": [ { "type": "ptp", "ipMasq": false, "ipam": { "type": "host-local", "dataDir": "/run/cni-ipam-state", "routes": [ { "dst": "0.0.0.0/0" } ], "ranges": [ [ { "subnet": "10.244.2.0/24" } ] ] } , "mtu": 1500 }, { "type": "portmap", "capabilities": { "portMappings": true } } ] } ] }
```
```
cat /etc/cni/net.d/10-kindnet.conflist
{
        "cniVersion": "0.3.1",
        "name": "kindnet",
        "plugins": [
        {
                "type": "ptp",
                "ipMasq": false,
                "ipam": {
                        "type": "host-local",
                        "dataDir": "/run/cni-ipam-state",
                        "routes": [
                                { "dst": "0.0.0.0/0" }
                        ],
                        "ranges": [
                                [ { "subnet": "10.244.2.0/24" } ]
                        ]
                }
                ,
                "mtu": 1500
        },
        {
                "type": "portmap",
                "capabilities": {
                        "portMappings": true
                }
        }
        ]
}
```

##### Device pool config file location (Try '/etc/pcidp/config.json')
```
{
  "resourceList": [{
    "resourceName": "sriov_net",
    "selectors": {
      "drivers": ["vfio-pci"],
      "pfNames": ["enp4s0f0","enp4s0f1"]
    }
  }]
}
```
##### Multus config (Try '/etc/cni/multus/net.d')
see ##### CNI config

##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
Kind deployment 

##### SR-IOV Network Custom Resource Definition
```
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: kubevirt.io/sriov_net
  name: sriov-network
spec:
  config: "{ \n    \"cniVersion\":\"0.3.1\", \n    \"name\":\"sriov-network\",\n
    \   \"type\":\"sriov\",\n    \"vlan\":0,\n    \"spoofchk\":\"on\",\n    \"trust\":\"off\",\n
    \   \"vlanQoS\":0,\n    \"link_state\":\"enable\",\n    \"ipam\":{}\n}"
```

##### Kubelet logs (journalctl -u kubelet)
Journal log including Multus logs from when the issue accord https://pastebin.com/eGhyrevk.

**Comment by ormergi** [comment]
Pod manifest for example: 
```
apiVersion: v1
kind: Pod
metadata:
  generateName: testpod-
  labels:
    test: pod1
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","mac":"02:02:02:02:02:02","name":"sriov-network","namespace":"default"}]'
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - sriov-worker2
  terminationGracePeriodSeconds: 0
  containers:
  - name: container1
    image: fedora
    command: ["sleep", "1000000"]
    resources:
      limits:
        kubevirt.io/sriov_net: "1"
      requests:
        kubevirt.io/sriov_net: "1"
```
