### ISSUE TITLE
Regression (commit 6217a32b62352c4ca506e7dc28ea886f2f1e9ecc) i.c.w. SRIOV operator

### ISSUE THREAD

**Issue by Omar007** [k8snetworkplumbingwg/sriov-cni#283]
### What happened?

Pods using very minimal SRIOV configuration (no vlans, no special `ipam` configs just dhcp) do not get initialized with the following error:

```
LoadConf(): non-zero vlan id must be configured to set vlan Qos and/or Proto
```

This traces back to a change in commit 6217a32b62352c4ca506e7dc28ea886f2f1e9ecc . Reverting sriov-cni to image tag `5ccf2aa2707b6be4e358d705f921994144117e5a` or earlier resolves the problem.

### What did you expect to happen?

Pod gets initialized normally as it did before, without throwing an error while vlan config isn't present in the first place.

### What are the minimal steps needed to reproduce the bug?

Update the sriov-cni image used by the operator to a tag containing commit 6217a32b62352c4ca506e7dc28ea886f2f1e9ecc .

### Anything else we need to know?

Component | Version|
------------------------------|--------------------|
|SR-IOV CNI Plugin            |latest|
|Multus                       |v4.0.2-thick|
|SR-IOV Network Device Plugin |latest|
|Kubernetes                   |1.28.2| 

##### SR-IOV Network Custom Resource Definition
```
kind: SriovNetwork
apiVersion: sriovnetwork.openshift.io/v1
metadata:
  name: intel-port1-vf
  namespace: sriov-network-operator
spec:
  resourceName: nic_intel_port1vf
  ipam: |
    {
      "type": "dhcp"
    }
```
