### ISSUE TITLE
SRIOV-CNI failed to configure VF "failed to set vf 0 vlan configuration - id 0, qos 0 and proto 802.1q: operation not supported"

### ISSUE THREAD

**Issue by zhutong196** [k8snetworkplumbingwg/sriov-cni#285]
##System:  centos:8

### device version
k8snetworkplumbingwg/sriov-network-device-plugin:latest-amd64

### multus-cni configuration
```
[root@xxx intel]# ls /etc/cni/net.d/
00-multus.conf  10-flannel.conflist  multus.d

[root@xxx intel]# more sriov-cm.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "mlnx_sriov",
                "resourcePrefix": "mellanox.com",
                "selectors": {
                    "vendors": ["15b3"],
                    "devices": ["101c"],
                    "drivers": ["mlx5_core"]
                }
            }
        ]
    }
```

### my pod yaml
```
[root@xxx intel]# more test-sriov-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: ib-sriov-pod
  annotations:
    v1.multus-cni.io/default-network: default/sriov-network
   #k8s.v1.cni.cncf.io/networks: sriov-network
spec:
  #nodeName: nma08-101-c-06-sev-nf5468-04u09
  nodeName: nma08-101-c-05-sev-nf5468-04u14
  containers:
  - name: testpod
    command:
    - tail
    - -f
    - /dev/null
    image: telecom.io/busybox
    resources:
      requests:
        mellanox.com/mlnx_sriov: '1'
      limits:
        mellanox.com/mlnx_sriov: '1'
```

### vf info

[root@xxx~]# lspci  -nn |grep Mella
35:00.0 Infiniband controller [0207]: Mellanox Technologies MT28908 Family [ConnectX-6] [15b3:101b]
35:00.1 Infiniband controller [0207]: Mellanox Technologies MT28908 Family [ConnectX-6 Virtual Function] [15b3:101c]
9c:00.0 Infiniband controller [0207]: Mellanox Technologies MT28908 Family [ConnectX-6] [15b3:101b]
9c:00.1 Infiniband controller [0207]: Mellanox Technologies MT28908 Family [ConnectX-6 Virtual Function] [15b3:101c]

###cause
<img width="1439" alt="image" src="https://github.com/k8snetworkplumbingwg/sriov-cni/assets/48009847/92e6fed2-60fc-4948-92ec-0d812585dd64">
